- README.markdown
- cmd/ddns.go
- internal/api/base.go
- internal/api/target.go
- internal/config/config.go
- internal/config/env.go
> Support IP4_DOMAINS and IP6_DOMAINS.

- README.markdown
- cmd/ddns.go
- internal/cron/printer.go
- internal/detector/cloudflare.go
> Use DNS-over-HTTPS

- README.markdown
- cmd/ddns.go
- internal/api/base.go
- internal/config/config.go
Unfortunately, the timeout would not really work until cloudflare/cloudflare-go#671 is fixed.
> Add CF_API_TIMEOUT and fix bugs

- README.markdown
- cmd/ip.go
- internal/config/config.go
> Add instructions for Kubernetes.

- .github/workflows/build.yaml
- Dockerfile
- cmd/ddns.go
> Print out the version

- .golangci.yaml
- README.markdown
- cmd/ddns.go
- cmd/ip.go
- internal/api/base.go
- internal/api/target.go
- internal/config/config.go
- internal/config/env.go
- internal/cron/printer.go
- internal/detector/cloudflare.go
- internal/detector/ipify.go
- internal/detector/local.go
- internal/detector/policy.go
- internal/detector/unmanaged.go
- internal/ipnet/ipnet.go
> Refactor code

- .golangci.yaml
- cmd/ddns.go
- cmd/ip.go
- cmd/priviledges.go
- internal/api/auth.go
- internal/api/base.go
- internal/api/update.go
- internal/config/config.go
- internal/config/env.go
- internal/cron/schedule.go
- internal/detector/dns.go
- internal/detector/ipify.go
- internal/detector/local.go
- internal/file/file.go
- internal/ipnet/ipnet.go
> Cache records

- .golangci.yaml
- cmd/ddns.go
- internal/api/auth.go
- internal/api/base.go
- internal/config/config.go
> Remove global variables and accept SIGHUP to restart

- README.markdown
- cmd/ddns.go
- internal/api/cloudflare.go
> docs: CloudFlare -> Cloudflare

- .github/workflows/build.yaml
- Dockerfile
New tags come with the "-alpine" suffix. This was inspired by #119.
> build: generate and upload larger images with debugging tools

- .github/workflows/build.yaml
> build: images for RISC-V

- .github/workflows/build.yaml
- Dockerfile
- README.markdown
Related: #121 and #122. Reported by @Macleykun in #119.
> build: fix the architecture of alpine-flavored images

- cmd/ip.go
- internal/api/base.go
- internal/api/cloudflare.go
- internal/api/cloudflare_test.go
- internal/detector/cloudflare_trace.go
- internal/detector/cloudflare_trace_test.go
- internal/detector/dns.go
- internal/detector/dns_test.go
- internal/detector/http.go
- internal/detector/http_test.go
- internal/detector/ip.go
- internal/detector/local.go
- internal/detector/local_test.go
- internal/detector/policy.go
- internal/ipnet/ipnet.go
- internal/ipnet/ipnet_test.go
- internal/updator/updator.go
- internal/updator/updator_test.go
> refactor: use net/netip

- .github/workflows/build.yaml
- Dockerfile
@Macleykun I am dropping the alpine images because they are no longer useful.
> Remove alpine images

- README.markdown
@Macleykun Does this look like what you would want?
> docs(README): more documentation on IPv6

- internal/file/file.go
- internal/file/file_test.go
> fix(file): accept absolute paths

- internal/config/config_test.go
(There's nothing wrong with the current code, but it should be tested.)
> test(config): test duplicate domains

- internal/api/cloudflare.go
- internal/api/cloudflare_test.go
- internal/pp/emoji.go
> fix(api): accept non-active zones

- internal/monitor/healthchecks_test.go
- internal/pp/fmt_test.go
> test: correct the order of arguments to require.Equal

- README.markdown
- internal/config/config_test.go
- internal/config/env.go
- internal/config/env_test.go
> fix: deprecate possibly unmaintained ipify

- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/build.sh
- .clusterfuzzlite/project.yaml
- .github/workflows/build.yaml
- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_cron.yml
- .github/workflows/cflite_pr.yml
- .github/workflows/cflite_prune.yml
- .github/workflows/test.yaml
- fuzzer/fuzzer.go
- internal/domainexp/parser.go
- internal/domainexp/parser_test.go
> ci(domainexp): add fuzzing for parsers

- README.markdown
- cmd/ddns.go
- internal/config/env.go
- internal/config/env_test.go
- internal/mocks/mock_pp.go
- internal/pp/base.go
- internal/pp/fmt.go
- internal/pp/fmt_test.go
> feat(pp): add an option to disable emojis

- README.markdown
- go.mod
- internal/provider/http.go
> feat(provider): auto retry IP detection

- cmd/ddns/ddns.go
- internal/droproot/drop.go
> refactor: split root dropping into its own package

- internal/api/cloudflare.go
- internal/api/cloudflare_test.go
> feat: annotate newly created DNS records

- internal/config/env_test.go
- internal/domainexp/lexer.go
- internal/domainexp/parser_test.go
- internal/monitor/composite_test.go
- internal/provider/protocol/http_test.go
- test/fuzzer/fuzzer_test.go
> test: improve coverage

- cmd/ddns/ddns.go
- internal/pp/emoji.go
> fix: print out something in the quiet mode

- CHANGELOG.markdown
- cmd/ddns/ddns.go
> fix: a better quiet mode notice

- .github/workflows/build.yaml
> ci: restore cosign

- internal/setter/setter.go
- internal/setter/setter_test.go
> fix(setter): quote DNS record IDs to prevent injection attacks

- .github/dependabot.yml
> ci: tell dependabot to group minor updates

- .github/dependabot.yml
> ci: fix dependabot.yml

- README.markdown
- go.mod
- internal/config/config_read.go
- internal/config/env_monitor.go
- internal/config/env_monitor_test.go
- internal/monitor/updatekuma.go
- internal/monitor/updatekuma_test.go
This reverts commit c267f9426799bdbffb4a1c8f3e29b9e1f4927d06. Close #599.
> feat: add support of Uptime Kuma

- README.markdown
Updated the Healthchecks & Uptime Kuma section with an additional note.
> Update README.markdown with IPv6 monitoring clarification

- README.markdown
- internal/config/network_probe.go
> docs: highlight how to disable IPv6

- internal/updater/updater.go
- internal/updater/updater_test.go
> feat(monitor): send "Failed to detect IPv4/6 address" to monitors

- internal/updater/updater.go
- internal/updater/updater_test.go
> feat(monitor): prioritize error messages

- cmd/ddns/ddns.go
- internal/mocks/mock_setter.go
- internal/setter/base.go
- internal/setter/setter.go
- internal/setter/setter_test.go
- internal/updater/updater.go
- internal/updater/updater_test.go
Related: #632. Message design: https://github.com/favonia/cloudflare-ddns/issues/641
> refactor: move message generation to updater (part 2 of shoutrrr support)

- .github/workflows/build.yaml
> build: add annotations

- README.markdown
- internal/api/cloudflare.go
- internal/api/cloudflare_test.go
- internal/pp/emoji.go
- internal/updater/updater.go
- internal/updater/updater_test.go
> docs: improve the hint for possibly incorrect account IDs

- internal/config/network_probe.go
- internal/config/network_probe_test.go
> docs: improve messages from network probing

- internal/provider/protocol/doh.go
> build: use math/rand/v2

- internal/domain/domain_test.go
> test(domain): capital cases

- cmd/ddns/ddns.go
- internal/config/config.go
- internal/config/network_probe.go
- internal/config/network_probe_test.go
- internal/updater/updater.go
- internal/updater/updater_test.go
> feat: recheck 1.1.1.1 versus 1.0.0.1 later when probing fails

- internal/provider/protocol/local_test.go
> test(provider): accept IPv6 link-local addresses during testing

- Dockerfile
> build(Dockerfile): set user and group IDs

- docs/DESIGN.markdown
- internal/setter/setter.go
- internal/setter/setter_test.go
> fix(setter): do not quote DNS record IDs

- cmd/ddns/ddns.go
- internal/api/cloudflare.go
- internal/api/cloudflare_records_test.go
- internal/api/cloudflare_test.go
> feat(api): check account IDs

- internal/api/cloudflare_records.go
- internal/api/cloudflare_records_test.go
This will completely prevent #691 from happening again!
> fix(api): decouple account IDs from operations on DNS records

- internal/provider/happy_eyeballs_test.go
> test(providor): test that Happy Eyeballs remembers its past choice

- internal/api/cloudflare_records.go
- internal/api/cloudflare_records_test.go
- internal/api/cloudflare_waf.go
- internal/api/cloudflare_waf_test.go
- internal/pp/hint.go
> docs: hint about permissions for DNS records

- README.markdown
> docs: document Kompose

- docs/DESIGN.markdown
- internal/api/cloudflare_records.go
- internal/api/cloudflare_records_test.go
- internal/api/cloudflare_test.go
- internal/api/cloudflare_waf.go
- internal/api/cloudflare_waf_test.go
- internal/monitor/uptimekuma.go
- internal/monitor/uptimekuma_test.go
- internal/setter/setter.go
- internal/setter/setter_test.go
> fix: reduce unnecessary quotations in logging

- internal/config/config.go
- internal/config/config_print.go
- internal/config/config_test.go
- internal/config/env_notifier.go
- internal/config/env_notifier_test.go
- internal/monitor/composite.go
- internal/monitor/composite_test.go
- internal/notifier/composite.go
- internal/notifier/composite_test.go
> fix: nil pointer bug introduced by commit 319e6a0 (issue #911)

- CHANGELOG.markdown
- go.mod
> docs: get ready to release 1.14.2

- internal/ipnet/ipnet.go
- internal/ipnet/ipnet_test.go
- internal/pp/hint.go
- internal/provider/protocol/http_test.go
- internal/provider/protocol/regexp_test.go
> fix(ipnet): reject IPv4-mapped IPv6 addresses used for IPv6

- cmd/ddns/ddns.go
- internal/config/env_auth.go
- internal/mocks/mock_pp.go
- internal/pp/base.go
- internal/pp/fmt.go
- internal/pp/fmt_test.go
- internal/pp/queued.go
- internal/pp/queued_test.go
> fix(pp): print blank lines to separate each round of updating

- README.markdown
Allow me to (try to) fix the README one more time... @carlox97
> docs(README): add "click to expand" to every collapsable text

- internal/provider/cloudflare_doh.go
- internal/provider/cloudflare_trace.go
> fix(provider): change cloudflare.{doh,trace} URLs

- README.markdown
Kompose 1.35.0 is released with the needed features!
> docs(README): update information about Kompose

- internal/config/env_domain_test.go
- internal/domain/domain.go
- internal/domain/domain_test.go
- internal/domain/fqdn_test.go
- internal/domainexp/parser.go
- internal/domainexp/parser_test.go
- test/fuzzer/fuzzer_test.go
> fix(domain): warn about domains that do not look like FQDNs

- internal/api/cloudflare_records.go
- internal/api/cloudflare_records_test.go
> fix: tweak warnings about mismatched attributes

- README.markdown
> docs(README): document Docker secrets

- internal/api/cloudflare_waf.go
- internal/api/cloudflare_waf_test.go
> feat(api): warn about non-empty WAF list item comments
