cmd/ddns.go
internal/cron/printer.go
internal/cron/schedule.go

Time durations such as  `1.938284s` would be printed as `about 2s`.

Better printing of time durations.

---

.github/workflows/build.yaml
Dockerfile

Needs Docker-Buildx 0.6.0. Blocked by actions/virtual-environments/pull/3792.

ci(docker): enable caching

---

README.markdown
internal/file/file.go
internal/file/file_test.go

Go 1.16 introduced `io/fs` and `testing/fstest` which already satisfy our needs. No need to use any external libraries.

test: use testing/fstest from std lib instead of spf13/afero

---

.github/workflows/build.yaml

Disable gha when building Docker images because a changing GIT_DESCRIBE seems to (correctly) invalidate cache every time.

ci: disable gha caching b/c GIT_DESCRIBE always invalidates it

---

README.markdown
internal/api/cloudflare.go
internal/api/cloudflare_test.go
internal/api/fqdn.go
internal/api/fqdn_test.go
internal/config/config.go
internal/updator/updator.go

test(api): test for package api

---

README.markdown
internal/config/config.go
internal/config/config_test.go
internal/config/env.go
internal/config/env_test.go
internal/detector/cloudflare_doh.go
internal/detector/cloudflare_doh_test.go
internal/detector/cloudflare_trace.go
internal/detector/cloudflare_trace_test.go

feat(detector): re-implement the cdn-cgi/trace parser

---

internal/api/cloudflare.go
internal/api/cloudflare_test.go

Token verification can fail even if the token is valid. For example, maybe the network is simply disconnected.

fix(cloudflare): revise the token verification message

---

cmd/ip.go

The context used in the old updateIP for setting IPs already has the timeout set for detection. The new code uses a fresh context for setting IPs. I believe this fixes #147.

fix: updating was wrongly restricted by detection timeout

---

.github/workflows/golangci-lint.yaml
.github/workflows/test.yaml
.golangci.yaml
go.mod
internal/api/domain.go
internal/config/config.go
internal/config/config_test.go
internal/config/env.go
internal/config/env_test.go
internal/monitor/base.go
internal/monitor/healthchecks.go
internal/monitor/healthchecks_test.go
internal/setter/setter.go

Waiting for the new release of golangci-lint

build: use Go 1.19

---

README.markdown
cmd/ddns.go
internal/README.markdown
internal/config/config.go
internal/config/config_test.go
internal/config/env.go
internal/config/env_test.go
internal/mocks/mock_monitor.go
internal/mocks/mock_setter.go
internal/monitor/base.go
internal/monitor/healthchecks.go
internal/monitor/healthchecks_test.go
internal/monitor/util.go
internal/monitor/util_test.go
internal/pp/emoji.go
internal/setter/base.go
internal/setter/setter.go
internal/setter/setter_test.go
internal/updater/updater.go
internal/updater/updater_test.go

1. Explicitly document that any instance of Healthchecks is supported
2. Warn about HTTP connections
3. Use POST method to work with the POST-only mode
4. Send summary for IP updating, record cleaning, and failures

feat(monitor): improve Healthchecks integration

---

README.markdown

This is to address the documentation issue I learned from #345. @truthsword

docs(README): make sure `PROXIED` is disabled for non-web servers

---

internal/api/cloudflare.go
internal/api/cloudflare_test.go

The testing should automatically pass with a new release of `cloudflare-go` with the above PR merged. (The optimization is small, but why not! :laughing:)

fix(api): optimize network traffic for UpdateRecord

---

.github/workflows/golangci-lint.yaml
.github/workflows/test.yaml
.golangci.yaml
README.markdown
go.mod
internal/domain/domain.go
internal/domainexp/parser.go
internal/domainexp/parser_test.go

refactor(domain): use strings.CutPrefix

---

README.markdown
cmd/ddns/ddns.go
go.mod
go.sum
internal/config/config.go
internal/config/config_test.go
internal/config/env.go
internal/config/env_test.go
internal/domainexp/lexer.go
internal/domainexp/parser.go
internal/domainexp/parser_test.go
internal/droproot/checker.go
internal/droproot/config.go
internal/droproot/drop.go
internal/pp/emoji.go
test/fuzzer/fuzzer_test.go

The single-run mode enabled by #411 (requested by #409) made it obvious that the quiet mode should be quieter. A few areas to improve:

fix: make the quiet mode quieter

---

.github/workflows/build.yaml

The device flow of Cosign is difficult to complete within GitHub Actions. (For example, if I open GitHub Actions logging too late, it is impossible for me to see the OIDC link before it fails.)

ci: remove Cosign from CI

---

.github/workflows/test.yaml
README.markdown
internal/ipnet/forceresolve.go
internal/ipnet/forceresolve_test.go
internal/ipnet/ipnet.go
internal/ipnet/ipnet_test.go
internal/provider/cloudflare_doh.go
internal/provider/cloudflare_trace.go
internal/provider/protocol/doh.go
internal/provider/protocol/field.go
internal/provider/protocol/field_test.go
internal/provider/protocol/http.go
internal/provider/protocol/http_test.go
internal/provider/protocol/httpcore.go

Some ISPs are still blocking 1.1.1.1, unfortunately. The new mechanism manually resolves the host `cloudflare-dns.com` as an IPv4 or IPv6 address, skipping the dual-stack switching in the Go standard library.

fix(provider): avoid static IPs such as 1.1.1.1

---

NOTICE
README.markdown
internal/config/network_probe.go

docs: fix various stuff

---

.github/workflows/build.yaml
.github/workflows/dependency-review.yml
.github/workflows/golangci-lint.yaml
.github/workflows/scorecards.yml
.github/workflows/test.yaml

The current policy is too strict for a non-maintainer to run CI.

ci: relax network blocking until someone else makes a PR

---

.github/workflows/build.yaml

After digging into the source code of ArtifactHub, I believe it doesn't make much sense to add ArtifactHub-specific annotations within individual image manifests. What should be changed is ArtifactHub, not this tool.
Since GitHub registry also expects annotations at the index level. 'manifest' was removed. This is reverting the PR #652.

fix: put annotations only within the index manifest

---

internal/provider/protocol/http.go

The idea was adapted from the following commit: https://github.com/gizmo-ds/cloudflare-ddns/commit/3a66d702eefe568d1da5c2f6ef2f2339d76551de
Thanks to @gizmo-ds

fix: trim the response of `url:URL` before parsing it

---

.github/workflows/test.yaml
cmd/ddns/ddns_test.go
internal/droproot/drop_test.go

test: undo the hacks that made Go 1.22.{0,1} work

---

cmd/ddns/ddns.go
internal/monitor/base.go
internal/monitor/composite.go
internal/monitor/composite_test.go

The bug was introduced in #762.

fix(monitor): distinguish success pinging from logging in SendResponse

---

cmd/ddns/ddns.go
internal/config/env_monitor_test.go
internal/monitor/uptimekuma.go
internal/monitor/uptimekuma_test.go

fix(monitor): a more powerful hack for quirks of Uptime Kuma

---

internal/api/base.go
internal/api/cloudflare.go
internal/api/cloudflare_test.go
internal/mocks/mock_api.go
internal/setter/setter.go
internal/setter/setter_test.go

Close #695. (Completely) close #680.

feat(setter): print '(cached)' for cached results

---

cmd/ddns/ddns.go
internal/api/base.go
internal/api/cloudflare.go
internal/api/cloudflare_test.go
internal/mocks/mock_api.go
internal/mocks/mock_setter.go
internal/setter/base.go
internal/setter/code.go
internal/setter/setter.go
internal/setter/setter_test.go

feat(api): recheck tokens when the network is temporarily down

---

cmd/ddns/ddns.go
internal/api/cloudflare.go
internal/api/cloudflare_test.go
internal/config/config_read.go
internal/config/config_read_test.go
internal/config/env_monitor_test.go
internal/domain/base.go
internal/domain/fqdn.go
internal/domain/fqdn_test.go
internal/domain/wildcard.go
internal/domain/wildcard_test.go
internal/monitor/healthchecks.go
internal/monitor/healthchecks_test.go
internal/monitor/uptimekuma.go
internal/monitor/uptimekuma_test.go
internal/provider/protocol/doh.go
internal/provider/protocol/doh_test.go
internal/provider/protocol/field.go
internal/provider/protocol/http.go
internal/provider/protocol/httpcore.go
internal/provider/protocol/local.go

It's also faster to pass structures directly except for really large ones.

refactor: remove unnecessary indirection

---

internal/api/base.go
internal/api/cloudflare.go
internal/api/cloudflare_records.go
internal/api/cloudflare_records_test.go
internal/api/cloudflare_waf.go
internal/api/cloudflare_waf_test.go
internal/mocks/mock_api.go
internal/setter/setter.go
internal/setter/setter_test.go

fix(api): make the updating algorithm more deterministic

---

.golangci.yaml
internal/api/cloudflare.go
internal/api/cloudflare_records.go
internal/api/cloudflare_records_test.go
internal/api/cloudflare_test.go
internal/api/cloudflare_waf.go
internal/api/cloudflare_waf_test.go
internal/config/check_root.go
internal/config/check_root_test.go
internal/config/config_print.go
internal/config/config_print_test.go
internal/config/config_read.go
internal/config/config_read_test.go
internal/config/network_probe.go
internal/config/network_probe_test.go
internal/ipnet/ipnet.go
internal/ipnet/ipnet_test.go
internal/mocks/mock_pp.go
internal/pp/base.go
internal/pp/fmt.go
internal/pp/fmt_test.go
internal/pp/hint.go
internal/pp/url.go
internal/provider/protocol/doh_test.go
internal/provider/protocol/field_test.go
internal/provider/protocol/http_test.go
internal/provider/protocol/local_test.go
internal/updater/updater.go
internal/updater/updater_test.go

refactor(pp): clean up pretty printing

---

internal/config/env_notifier.go
internal/config/env_notifier_test.go
internal/config/env_provider.go
internal/config/env_provider_test.go
internal/config/env_waf.go
internal/config/env_waf_test.go
internal/pp/hint.go

docs: warn about using experimental features

---

README.markdown
internal/config/config_read_test.go
internal/config/env_auth.go
internal/config/env_auth_test.go
internal/pp/hint.go

feat(config): accept CLOUDFLARE_* and all compatible token settings

---

CONTRIBUTORS.markdown

@JvdMaat I'm not sure whether my rewriting "solved" the copyright issue, or whether there's an issue at all to begin with, but I want to thank people as much as possible. :-) I took that you are fine with the LLVM exceptions.
Related: #952.

docs(CONTRIBUTORS): re-recognize JvdMaat's contribution

---

.golangci.yaml
docs/DESIGN.markdown
internal/api/cloudflare_records_test.go
internal/api/cloudflare_waf_test.go
internal/config/check_root_test.go
internal/config/config_read_test.go
internal/config/env_auth.go
internal/config/env_auth_test.go
internal/config/env_base_test.go
internal/config/env_domain_test.go
internal/config/env_monitor_test.go
internal/config/env_notifier_test.go
internal/config/env_provider_test.go
internal/config/env_waf_test.go
internal/domainexp/parser_test.go
internal/ipnet/ipnet_test.go
internal/monitor/healthchecks_test.go
internal/monitor/uptimekuma_test.go
internal/notifier/shoutrrr_test.go
internal/provider/protocol/doh_test.go
internal/provider/protocol/http_test.go
internal/provider/protocol/local_auto_test.go
internal/provider/protocol/local_iface_test.go
internal/provider/protocol/regexp_test.go
internal/setter/setter_test.go
internal/updater/updater_test.go
test/fuzzer/fuzzer_test.go

I'm getting tired of the `lll` linter for `*_test.go` files :upside_down_face:

ci: lint the linters
